# [optional] the ID of the GitHub Project to add new issues to
project = 5

[repo]
# The GitHub username of the repo owner
owner = "piemot"
# If the owner is an org, use:
# owner = { type = "organization", login = "piemot" }

# The name of the repository
repo = "sample"

[[users]]
trello = "piemot"
github = "piemot"


[[lists]]
# The name or ID of the Trello list
list = "Bugs"
# The name or ID of the equivalent GitHub label
label = "bug"

[[lists]]
# The name or ID of the Trello list
list = "Done"
# The name or ID of the equivalent GitHub Project Status (requires `project` to be set above)
status = "Done"

[[lists]]
list = "Suggestions"
status = "In Progress"


[[labels]]
# The name of the Trello label
trello = "High Priority"
# The name or ID of the equivalent GitHub label
github = 9000084910

[[labels]]
trello = "Med. Priority"
github = 9000085331

[[labels]]
trello = "Low Priority"
github = 9000085739

[[labels]]
trello = "Enhancement"
github = 8999843230

[[labels]]
trello = "New Feature"
github = 8999843230

[[labels]]
trello = "Bug"
github = 8999843222

[[labels]]
trello = "No Repro"
github = 9000089270

[[labels]]
trello = "Patreon Locked"
github = 9000090739

[[labels]]
trello = "RFC"
github = 8999843233

[[members]]
trello = "piemot"
github = "piemot"
