# [optional] the ID of the GitHub Project to add new issues to
project = 6

[repo]
# The GitHub username of the repo owner
owner = "piemot"
# If the owner is an org, use:
# owner = { type = "organization", login = "piemot" }

# The name of the repository
repo = "trello-migration-test"


[skip]
lists = ["Key", "Done"]


[[users]]
trello = "piemot"
github = "piemot"

# [[users]]
# trello = "geheimerwolf"
# github = "GeheimerWolf"


[[lists]]
# The name or ID of the Trello list
list = "Bugs"
# The name or ID of the equivalent GitHub label
label = "bug"

[[lists]]
# The name or ID of the Trello list
list = "Backlog"
# The name or ID of the equivalent GitHub Project Status (requires `project` to be set above)
status = "Backlog"

[[lists]]
list = "Suggestions"
status = "Backlog"

[[lists]]
list = "Work in Progress"
status = "In progress"


[[labels]]
# The name of the Trello label
trello = "High Priority"
# The name or ID of the equivalent GitHub label
github = "P0"

[[labels]]
trello = "Med. Priority"
github = "P1"

[[labels]]
trello = "Low Priority"
github = "P2"

[[labels]]
trello = "Enhancement"
github = "enhancement"

[[labels]]
trello = "New Feature"
github = "enhancement"

[[labels]]
trello = "Bug"
github = "bug"

[[labels]]
trello = "No Repro"
github = "invalid"

[[labels]]
trello = "Patreon Locked"
github = "Premium"

[[labels]]
trello = "RFC"
github = "question"
